strings = {"home_title": "Identificação Automatizada Da Composição Corporal",
            "home_description": "Selecione pastas contendo arquivos DICOM de exames tomográficos para determinação automatica da composição corporal dos pacientes",
            "home_button": "Iniciar",
            "path_select_title": "Adicione os arquivos",
            "path_select_add_button": "Adicionar",
            "path_select_remove_button": "X",
            "path_select_remove_all_button": "Remover todos",
            "path_select_start_button": "Começar",
            "processing_title": "Processamento em andamento",
            "processing_description": "Aguarde enquanto selecionamos a L3 e mapeamos os tecidos",
            "processing_file_path_header": "Caminho",
            "processing_tc_id_header": "Caminho",
            "processing_date_info_header": "Data",
            "processing_file_path_header": "Caminho",
            "processing_title": "Processamento em andamento",}
print(strings["home_description"])