## strings used on all screens
strs = {"home_title": "Identificação Automatizada Da Composição Corporal",
          "home_description": "Selecione pastas contendo arquivos DICOM de exames tomográficos para determinação automatica da composição corporal dos pacientes",
          "home_button": "Iniciar",
          "save_path_select_title": "Salvar em",
          "save_path_select_button": "Escolher",
          "path_select_title": "Adicione diretórios contendo exames de Tomografia",
          "path_select_add_button": "Adicionar",
          "path_select_remove_button": "X",
          "path_select_remove_all_button": "Remover todos",
          "path_select_start_button": "Confirmar",
          "processing_title": "Processamento em andamento",
          "processing_description": "Aguarde enquanto selecionamos a L3 e mapeamos os tecidos",
          "processing_file_path_header": "Caminho",
          "processing_tc_id_header": "ID",
          "processing_date_header": "Data",
          "processing_description_header": "Descrição",
          "processing_status_header": "Status",
          "processing_status_ongoing": "...",
          "processing_status_success": "✅",
          "processing_status_failed": "❎",
          "processing_final_button":"Ver Resultados",
          "results_title":"Resultados",
          "results_description":"Resultados",
          "results_button_back":"Voltar ao Início",
          "results_metric_header_muscle":"Muscle",
          "results_metric_header_imat":"IMAT",
          "results_metric_header_vat":"VAT",
          "results_metric_header_sat":"SAT",
          "results_metric_unit_hu":"HU",
          "results_metric_unit_cm2":"cm²",
          "results_save_path_description":"Resultados salvos em: ",
          }
##print(strs["home_description"])